### ISSUE TITLE
Does not compile with Node V0.6.0

### ISSUE THREAD

**Issue by jfd** [node-inspector/v8-profiler#9]
> v8-profiler@0.0.3 preinstall /usr/local/lib/node_modules/v8-profiler
> node-waf clean || true; node-waf configure build

Nothing to clean (project not configured)
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node_modules 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.029s)
Waf: Entering directory `/usr/local/lib/node_modules/v8-profiler/build'
[1/9] cxx: snapshot.cc -> build/Release/snapshot_1.o
[2/9] cxx: graph_edge.cc -> build/Release/graph_edge_1.o
[3/9] cxx: graph_node.cc -> build/Release/graph_node_1.o
[4/9] cxx: graph_path.cc -> build/Release/graph_path_1.o
[5/9] cxx: snapshot_diff.cc -> build/Release/snapshot_diff_1.o
[6/9] cxx: profile.cc -> build/Release/profile_1.o
[7/9] cxx: profile_node.cc -> build/Release/profile_node_1.o
[8/9] cxx: profiler.cc -> build/Release/profiler_1.o
In file included from ../snapshot_diff.cc:1:
../snapshot_diff.h:15: error: expected ‘,’ or ‘...’ before ‘*’ token
../snapshot_diff.h:15: error: ISO C++ forbids declaration of ‘HeapSnapshotsDiff’ with no type
In file included from ../graph_path.cc:1:
../graph_path.h:15: error: expected ‘,’ or ‘...’ before ‘*’ token
../graph_path.h:15: error: ISO C++ forbids declaration of ‘HeapGraphPath’ with no type
In file included from ../snapshot.cc:2:
../snapshot_diff.h:15: error: expected ‘,’ or ‘...’ before ‘*’ token
../snapshot_diff.h:15: error: ISO C++ forbids declaration of ‘HeapSnapshotsDiff’ with no type
../snapshot_diff.cc: In static member function ‘static v8::Handle<v8::Value> nodex::SnapshotDiff::GetAdditions(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../snapshot_diff.cc:21: error: expected type-specifier before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:21: error: expected`>' before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:21: error: expected `(' before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:21: error: ‘HeapSnapshotsDiff’ was not declared in this scope
../snapshot_diff.cc:21: error: expected primary-expression before ‘>’ token
../snapshot_diff.cc:21: error: ‘void*’ is not a pointer-to-object type
../snapshot_diff.cc:21: error: expected`)' before ‘;’ token
../snapshot_diff.cc: In static member function ‘static v8::Handlev8::Value nodex::SnapshotDiff::GetDeletions(v8::Localv8::String, const v8::AccessorInfo&)’:
../snapshot_diff.cc:29: error: expected type-specifier before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:29: error: expected `>' before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:29: error: expected`(' before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:29: error: ‘HeapSnapshotsDiff’ was not declared in this scope
../snapshot_diff.cc:29: error: expected primary-expression before ‘>’ token
../snapshot_diff.cc:29: error: ‘void_’ is not a pointer-to-object type
../snapshot_diff.cc:29: error: expected `)' before ‘;’ token
In file included from ../graph_node.cc:3:
../graph_path.h:15: error: expected ‘,’ or ‘...’ before ‘_’ token
../graph_path.h:15: error: ISO C++ forbids declaration of ‘HeapGraphPath’ with no type
../snapshot_diff.cc: At global scope:
../snapshot_diff.cc:33: error: expected ‘,’ or ‘...’ before ‘_’ token
../snapshot_diff.cc:33: error: ISO C++ forbids declaration of ‘HeapSnapshotsDiff’ with no type
../snapshot_diff.cc: In static member function ‘static v8::Handlev8::Value nodex::SnapshotDiff::New(int)’:
../snapshot_diff.cc:40: error: ‘diff’ was not declared in this scope
../snapshot_diff.cc:45: error: expected type-specifier before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:45: error: expected `>' before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:45: error: expected`(' before ‘HeapSnapshotsDiff’
../snapshot_diff.cc:45: error: expected primary-expression before ‘>’ token
../graph_path.cc: In static member function ‘static v8::Handlev8::Value nodex::GraphPath::GetEdgesCount(v8::Localv8::String, const v8::AccessorInfo&)’:
../graph_path.cc:24: error: expected type-specifier before ‘HeapGraphPath’
../graph_path.cc:24: error: expected `>' before ‘HeapGraphPath’
../graph_path.cc:24: error: expected`(' before ‘HeapGraphPath’
../graph_path.cc:24: error: ‘HeapGraphPath’ was not declared in this scope
../graph_path.cc:24: error: expected primary-expression before ‘>’ token
../graph_path.cc:24: error: ‘void_’ is not a pointer-to-object type
../graph_path.cc:24: error: expected `)' before ‘;’ token
../graph_path.cc: In static member function ‘static v8::Handle<v8::Value> nodex::GraphPath::GetEdge(const v8::Arguments&)’:
../graph_path.cc:38: error: expected type-specifier before ‘HeapGraphPath’
../graph_path.cc:38: error: expected`>' before ‘HeapGraphPath’
../graph_path.cc:38: error: expected `(' before ‘HeapGraphPath’
../graph_path.cc:38: error: ‘HeapGraphPath’ was not declared in this scope
../graph_path.cc:38: error: expected primary-expression before ‘>’ token
../graph_path.cc:38: error: ‘void*’ is not a pointer-to-object type
../graph_path.cc:38: error: expected`)' before ‘;’ token
../graph_path.cc: In static member function ‘static v8::Handlev8::Value nodex::GraphPath::GetFromNode(v8::Localv8::String, const v8::AccessorInfo&)’:
../graph_path.cc:46: error: expected type-specifier before ‘HeapGraphPath’
../graph_path.cc:46: error: expected `>' before ‘HeapGraphPath’
../snapshot.cc: In static member function ‘static v8::Handle<v8::Value> nodex::Snapshot::GetType(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../snapshot.cc:56: error: ‘kAggregated’ is not a member of ‘v8::HeapSnapshot’
../graph_path.cc:46: error: expected`(' before ‘HeapGraphPath’
../graph_path.cc:46: error: ‘HeapGraphPath’ was not declared in this scope
../snapshot.cc: In static member function ‘static v8::Handlev8::Value nodex::Snapshot::CompareWith(const v8::Arguments&)’:
../snapshot.cc:78: error: expected initializer before ‘_’ token
../snapshot.cc:79: error: ‘diff’ was not declared in this scope
../graph_path.cc:46: error: expected primary-expression before ‘>’ token
../graph_path.cc:46: error: ‘void_’ is not a pointer-to-object type
../graph_path.cc:46: error: expected `)' before ‘;’ token
../graph_path.cc: In static member function ‘static v8::Handle<v8::Value> nodex::GraphPath::GetToNode(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../graph_path.cc:54: error: expected type-specifier before ‘HeapGraphPath’
../graph_path.cc:54: error: expected`>' before ‘HeapGraphPath’
../graph_path.cc:54: error: expected `(' before ‘HeapGraphPath’
../graph_path.cc:54: error: ‘HeapGraphPath’ was not declared in this scope
../graph_path.cc:54: error: expected primary-expression before ‘>’ token
../graph_path.cc:54: error: ‘void*’ is not a pointer-to-object type
../graph_path.cc:54: error: expected`)' before ‘;’ token
../graph_path.cc: At global scope:
../graph_path.cc:58: error: expected ‘,’ or ‘...’ before ‘_’ token
../graph_path.cc:58: error: ISO C++ forbids declaration of ‘HeapGraphPath’ with no type
../graph_path.cc: In static member function ‘static v8::Handlev8::Value nodex::GraphPath::New(int)’:
../graph_path.cc:65: error: ‘path’ was not declared in this scope
../graph_path.cc:70: error: expected type-specifier before ‘HeapGraphPath’
../graph_path.cc:70: error: expected `>' before ‘HeapGraphPath’
../graph_path.cc:70: error: expected`(' before ‘HeapGraphPath’
../graph_path.cc:70: error: expected primary-expression before ‘>’ token
../graph_node.cc: In static member function ‘static v8::Handlev8::Value nodex::GraphNode::GetInstancesCount(v8::Localv8::String, const v8::AccessorInfo&)’:
../graph_node.cc:93: error: ‘class v8::HeapGraphNode’ has no member named ‘GetInstancesCount’
../graph_node.cc: In static member function ‘static v8::Handlev8::Value nodex::GraphNode::GetRetainingPathsCount(v8::Localv8::String, const v8::AccessorInfo&)’:
../graph_node.cc:165: error: ‘class v8::HeapGraphNode’ has no member named ‘GetRetainingPathsCount’
../graph_node.cc: In static member function ‘static v8::Handlev8::Value nodex::GraphNode::GetRetainingPath(const v8::Arguments&)’:
../graph_node.cc:179: error: expected initializer before ‘_’ token
../graph_node.cc:180: error: ‘path’ was not declared in this scope
../profiler.cc: In function ‘v8::Handlev8::Value TakeSnapshot(const v8::Arguments&)’:
../profiler.cc:15: error: ‘kAggregated’ is not a member of ‘v8::HeapSnapshot’
Waf: Leaving directory `/usr/local/lib/node_modules/v8-profiler/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx snapshot_diff.cc -> snapshot_diff_1.o}
 -> task failed (err #1): 
    {task: cxx snapshot.cc -> snapshot_1.o}
 -> task failed (err #1): 
    {task: cxx graph_path.cc -> graph_path_1.o}
 -> task failed (err #1): 
    {task: cxx graph_node.cc -> graph_node_1.o}
 -> task failed (err #1): 
    {task: cxx profiler.cc -> profiler_1.o}
npm ERR! error installing v8-profiler@0.0.3 Error: v8-profiler@0.0.3 preinstall:`node-waf clean || true; node-waf configure build`
npm ERR! error installing v8-profiler@0.0.3`sh "-c" "node-waf clean || true; node-waf configure build"`failed with 1
npm ERR! error installing v8-profiler@0.0.3     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing v8-profiler@0.0.3     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing v8-profiler@0.0.3     at maybeExit (child_process.js:359:16)
npm ERR! error installing v8-profiler@0.0.3     at Process.onexit (child_process.js:395:5)
npm ERR! v8-profiler@0.0.3 preinstall:`node-waf clean || true; node-waf configure build`
npm ERR!`sh "-c" "node-waf clean || true; node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the v8-profiler@0.0.3 preinstall script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "v8-profiler"
npm ERR! cwd /Users/jfd/workspace/beruntime
npm ERR! node -v v0.6.0
npm ERR! npm -v 1.0.104
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jfd/workspace/beruntime/npm-debug.log
npm not ok
