### ISSUE TITLE
Does not compile with Node V0.10.12

### ISSUE THREAD

**Issue by yorkie** [node-inspector/v8-profiler#30]
```
> v8-profiler@3.6.2-1 install /usr/local/lib/node_modules/v8-profiler
> node-gyp rebuild

  CXX(target) Release/obj.target/profiler/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/graph_edge.o
  CXX(target) Release/obj.target/profiler/graph_node.o
../graph_node.cc:99:53: error: no member named 'GetRetainersCount' in
      'v8::HeapGraphNode'
  int32_t count = static_cast<HeapGraphNode*>(ptr)->GetRetainersCount();
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:132:52: error: no member named 'GetRetainedSize' in
      'v8::HeapGraphNode'
  int32_t size = static_cast<HeapGraphNode*>(ptr)->GetRetainedSize();
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:154:65: error: no member named 'GetRetainer' in
      'v8::HeapGraphNode'
  ...edge = static_cast<HeapGraphNode*>(ptr)->GetRetainer(index);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:162:65: error: no member named 'GetDominatorNode' in
      'v8::HeapGraphNode'
  ...node = static_cast<HeapGraphNode*>(ptr)->GetDominatorNode();
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
4 errors generated.
make: *** [Release/obj.target/profiler/graph_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/v8-profiler
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```
